### ISSUE TITLE
Backup module for all meta data

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-android#6552]
Take existing contacts backup module and extend it to all app metadata. There should be a single module (accessible from app settings) to backup app all app metadata:

- [ ] payment contacts
- [ ] coins in the watchlist
- [ ] watched wallets
- [ ] app appearance settings
- [ ] app security settings

## 1) New Manage Wallets Implementation

- [x] **Import Wallet**
- from Recovery Phrase
- from Files
- from Exchange
<img width="162" alt="Screenshot 2023-09-28 at 17 58 36" src="https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22589457/249fcb8c-1896-43e4-ab27-d307ff295dbd">

- [x] Add the "Backup Manager" section to the Settings
<img width="182" alt="Screenshot 2023-09-28 at 18 12 24" src="https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22589457/e43c7363-cfc3-46a6-9493-b79fbb12c165">

## 2) Backup Manager -- Create

- [x] **Creating a new backup app:** Users can choose to create backups of their wallets, contacts, and application settings to avoid any data loss. This feature allows users to save their backups directly to their device's system file manager, making them easily accessible and manageable.

- [x] **Selective Backup:** Users have the option to choose which wallets they want to include in the backup. By default, other settings such as watch wallets, contacts, and blockchain settings will also be backed up.

- [ ]  Text Backup to Files
> Storage devices i.e. hard drives, USB drives, storage on smartphones, etc. are all vulnerable to loss due to physical damage, theft, or other unforeseen circumstances.
>> I understand that theft or damage of a backup device will result in the loss of a backup to a respective wallet.

- [x] **Setting a Password:** When creating a backup, users will be required to set a password, which must consist of at least 8 characters.

- [x] **Notification and Redirection:** After successfully creating a backup, users will receive a notification and will be redirected to the "Backup Manager" page to manage their backups.

## 3) **Backup Manager -- Restore** 

Currently, our application has two locations where users can restore the backup app. 

- Manage Wallet -> Import Wallet
This location will primarily focus on wallet restoration but will also include the option to restore other settings.

- "Settings -- Backup Manager
This location will be dedicated to creating and restoring backups, including wallets, contacts, and other application settings.

### **From Files**

- [ ] When selecting this option, the user will be directed to the system file manager page.

- [ ] To restore a file, the user needs to enter the password associated with the corresponding backup.

- [ ] After successfully entering the password, the contents of the backup file will be revealed.

- [ ] If the user already has restored wallets and contacts and wishes to restore another backup file, a notification with a bottom shield will appear, prompting the user to merge the data.
